# set base image (host OS)
FROM python:3.8

# set the working directory in the container
WORKDIR /code/django

# copy the dependencies file to the working directory
COPY ./django/requirements.txt .

# install dependencies
RUN pip install -r requirements.txt

# copy the content of the local src directory to the working directory
COPY ./django .

COPY ./dao ../dao

# command to run on container start
CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]