version: "3.7"
services:
  database:
    hostname: database
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    networks:
      - bachelor
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
  spring: 
    hostname: spring
    container_name: spring
    build: 
      context: ./backend/java
      dockerfile: spring/Dockerfile
    ports:
      - 8081:8080
    networks: 
      - bachelor
  jersey: 
    hostname: jersey
    container_name: jersey
    build: 
      context: ./backend/java
      dockerfile: jaxrs/Dockerfile
    ports:
      - 8082:8080
    networks: 
      - bachelor
  laravel: 
    hostname: laravel
    container_name: laravel
    build: 
      context: ./backend/php
      dockerfile: laravel/Dockerfile
    ports:
      - 8083:8000
    networks: 
      - bachelor
  code-igniter: 
    hostname: code-igniter
    container_name: code-igniter
    build: 
      context: ./backend/php
      dockerfile: code-igniter/Dockerfile
    ports:
      - 8084:8080
    networks: 
      - bachelor
  express: 
    hostname: express
    container_name: express
    build: 
      context: ./backend/js
      dockerfile: express/Dockerfile
    ports:
      - 8085:8080
    networks: 
      - bachelor
  restify: 
    hostname: restify
    container_name: restify
    build: 
      context: ./backend/js
      dockerfile: restify/Dockerfile
    ports:
      - 8086:8080
    networks: 
      - bachelor
  asp-net: 
    hostname: asp-net
    container_name: asp-net
    build: 
      context: ./backend/csharp
      dockerfile: asp-net/Dockerfile
    ports:
      - 8087:80
    networks: 
      - bachelor
  flask: 
    hostname: flask
    container_name: flask
    build: 
      context: ./backend/python
      dockerfile: flask_app/Dockerfile
    ports:
      - 8088:5000
    networks: 
      - bachelor
  django: 
    hostname: django
    container_name: django
    build: 
      context: ./backend/python
      dockerfile: django/Dockerfile
    ports:
      - 8089:8000
    networks: 
      - bachelor
  frontend: 
    hostname: frontend
    container_name: frontend
    build: 
      context: ./frontend
    ports:
      - 8080:8080
networks: 
  bachelor:


