FROM php:7.4-cli-alpine3.12

RUN set -ex \
  && apk --no-cache add \
    postgresql-dev
RUN docker-php-ext-install pgsql pdo_pgsql

COPY ./laravel /usr/src/laravel
COPY ./dao /usr/src/dao

WORKDIR /usr/src/laravel
EXPOSE 8000
CMD [ "php", "artisan", "serve" ]